# Generated by Django 6.0.2 on 2026-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_booking_created_at_listing_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='max_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('room', 'Room'), ('studio', 'Studio')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='square_meters',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
