# Generated by Django 5.2.10 on 2026-04-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_remove_listing_status_listing_bathrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="available_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="available_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
