# Generated by Django 6.0.3 on 2026-05-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_available_from_listing_available_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guests",
            field=models.IntegerField(default=1),
        ),
    ]
