# Generated by Django 6.0.1 on 2026-05-11 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_booking_guests"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOnService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("airport_transfer", "Airport Transfer"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
